version: '3.8'

services:
  web:
    build: .
    command: gunicorn -b 0.0.0.0:5002 --timeout 120 hbnb:app
    volumes:
      - .:/app
    ports:
      - "5002:5002"
    environment:
      - FLASK_APP=hbnb.py
      - ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/prod_db
      - JWT_SECRET_KEY=Anibalhola
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: prod_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: