"""Remove place_amenity relationship

Revision ID: 5423ee7cbbd4
Revises: 8a2cd8287f9b
Create Date: 2024-06-26 12:04:03.852942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5423ee7cbbd4'
down_revision: Union[str, None] = '8a2cd8287f9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
